# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassador', '0002_auto_20161215_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='EmailAdd',
            new_name='Email_Address',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='collegeAddress',
            new_name='college_Address',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='collegName',
            new_name='college_Name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='facebookLink',
            new_name='facebook_Link',
        ),
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
